spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce-db
spring.datasource.username=postgres
spring.datasource.password=1111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

jwt.secret=myVeryLongSecretKeyForJwtAuthentication12345678901234567890
jwt.expiration=86400000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

file.upload-dir=uploads

razorpay.key.id=rzp_test_T7KSSSSXjryRDz
razorpay.key.secret=bjqG57WoKqqA4R2omTng5A8y



#########################################
# EMAIL CONFIGURATION
#########################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=rigvedam07@gmail.com
spring.mail.password=rqto wghs ktmi qcov

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

mail.from=suhaspai412@gmail.com